### ISSUE TITLE
Dev mode not installing features after change to server.xml

### ISSUE THREAD

**Issue by rzgry** [OpenLiberty/ci.gradle#416]
```
Copied file: /Users/rzegray/Developer/devex/demo-devmode/src/main/liberty/config/server.xml to: /private/var/folders/x6/tc6_9wj567541sczlplbv6jw0000gn/T/tempConfig1945666673317461456/server.xml

> Task :installLiberty UP-TO-DATE
> Task :libertyCreate
[AUDIT   ] CWWKG0016I: Starting server configuration update.
[ERROR   ] CWWKF0001E: A feature definition could not be found for mphealth-2.0
[AUDIT   ] CWWKG0017I: The server configuration was successfully updated in 0.127 seconds.
[AUDIT   ] CWWKF0008I: Feature update completed in 0.112 seconds.

> Task :installFeature
```

**Comment by ericglau** [comment]
This looks like a regression caused by https://github.com/OpenLiberty/ci.gradle/pull/398.  Reverting that change would avoid this issue.

**Comment by ericglau** [comment]
The issue is #398 caused installFeature to depend on libertyCreate, and libertyCreate to be finalized by installFeature.  So the server is created before the features are installed, which causes an error.

Instead, the order should be: install Liberty runtime, then install features, then create the server.
So libertyCreate should depend on installFeature, and installFeature should depend on installLiberty.
