### ISSUE TITLE
Generated keystore_password in server.env overwritten when combined with env configuration

### ISSUE THREAD

**Issue by cmuchinsky** [OpenLiberty/ci.gradle#459]
It looks like the logic in `AbstractServerTask.copyConfigFiles` is overwriting the generated values stored in the `server.env` file during server creation. If a `server.env` exists in the default config directory, or if the server extension has inline values or a file, the generated `keystore_password` value is always lost.

**Comment by cherylking** [comment]
It is true if a `server.env` file is specified or there are inline values, that will cause the existing `server.env` file to get overwritten and it will not contain the generated `keystore_password`. That is intended behavior. Would any of the other locations used for server environment variables help you?

<img width="961" alt="Screen Shot 2020-06-07 at 9 20 01 PM" src="https://user-images.githubusercontent.com/29436451/83987131-debb4680-a904-11ea-85f3-08fa3334c59c.png">

**Comment by cmuchinsky** [comment]
From what I can tell, the expected behavior from the liberty command itself is to merge the `server.env` contents (see https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/BootstrapConfig.java#L1213), but for the gradle task you are saying it will never work that way?

**Comment by cherylking** [comment]
The way the plugins were designed presumed that if a config file or inline configuration is specified, then that is the configuration to be used, not some default configuration provided by the creation of the server. Also, if you run multiple server commands, we update the configuration each time in case the config has changed. If we appended to existing files, that would not have the correct result. 

Perhaps we can add a parameter to indicate the server.env file should be appended to since it seems to be a special case, and keep a backup of the original file for further updates? I wouldn't want this behavior to extend to all the other config files though.

**Comment by cherylking** [comment]
After discussing with our team, we propose adding an `appendServerEnv` attribute that defaults to `false`. If it is specified as `true`, we will preserve the original contents of the generated `server.env` file and append the inline config or config file to it. An exception to this is if a `keystore_password` is specified in the inline config or config file, then it overwrites the original default one that was generated upon server creation.
