### ISSUE TITLE
Cannot programmatically get output file from libertyPackage task

### ISSUE THREAD

**Issue by cmuchinsky** [OpenLiberty/ci.gradle#472]
I'm unable to get access to the output of the libertyPackage task using the task's `outputs` property as is standard with most gradle tasks. I suspect this is because the task is missing logic to declare its outputs. Adding this might also ensure that gradle's up-to-date logic works properly as well. This issue was discovered with the following line of gradle code:
```
libertyPackage.outputs.files.singleFile
```
Which produces this error:
```
Expected task 'libertyPackage' output files to contain exactly one file, however, it contains no files.
```

**Comment by ind1go** [comment]
Just came across this myself - would be great to see this task having an output, as it would make it easier to wire tasks together and also, at the moment, the task is never `UP-TO-DATE` because it has no outputs defined, so it will always run.

I'm having to set it up manually which isn't great, replicating logic from [here](https://github.com/OpenLiberty/ci.gradle/blob/main/src/main/groovy/io/openliberty/tools/gradle/tasks/PackageTask.groovy#L120):

```groovy
private String getPackageName() {
    if (liberty.server.packageLiberty.packageName != null && !liberty.server.packageLiberty.packageName.isEmpty()) {
        return liberty.server.packageLiberty.packageName
    }
    return project.getName()
}

def packageDir = new File(project.getBuildDir(), 'libs')
def packageFile = new File(packageDir, getPackageName())
tasks.getByPath(':libertyPackage').outputs.file(packageFile)
```
