### ISSUE TITLE
Appveyor tests are failing

### ISSUE THREAD

**Issue by evie-lau** [OpenLiberty/ci.gradle#497]
It seems the main issues for the appveyor tests are:

- tests that check for `/commons-text-1.1.jar` in the TestLoose*Application tests
- PollingDevTest as mentioned in #439

**Comment by cherylking** [comment]
We previously moved the PollingDevTest to the Gradle 4.10 wrapper section of the build as they were passing there. But now they fail due to an API that is not available on that level. I'm going to remove the PollingDevTest from the AppVeyor builds because of this.

<img width="913" alt="Screen Shot 2020-11-19 at 8 04 55 AM" src="https://user-images.githubusercontent.com/29436451/99676510-37f3de00-2a3e-11eb-999d-826e0a40f149.png">

**Comment by cherylking** [comment]
We no longer run tests on Appveyor.
