### ISSUE TITLE
Strategy to not hardcode webApplication location war file name?

### ISSUE THREAD

**Issue by sreich** [OpenLiberty/ci.gradle#838]
Hello, i'm looking into not hardcoding the following line in server.xml,. the location element:

     <webApplication contextRoot="myservlet" id="ServletSample" location="myservlet-0.9-SNAPSHOT.war"/>

What are your thoughts on the optimal approach for it? From the docs, it looks like I cannot do a wildcard on myservlet*

My thinking is, add a `bootstrapProperties["my.app.war"] = <find war file name>`...because it is in bootstrap, it would work in a dockerized environment, too (as opposed to say, just setting a `<variable>` inside server.xml but then it not getting resolved outside of a gradle context without additional docker env vars (i.e. docker image, which just does a dumb `COPY`)

Seem reasonable or is there an even nicer approach?

**Comment by cherylking** [comment]
We do use variable substitution for the `location` in some of our test cases. So it seems reasonable. You can easily set the property in the `bootstrap.properties` file from the `build.gradle` also so that it does not need to be hardcoded there either. It could be determined from the project name or artifactId.

**Comment by sreich** [comment]
Okay excellent, thank you
